apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.17.255.53
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: tcp2
      protocol: TCP
      port: 9153
      targetPort: 9153