---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-jane           # под этим именем мы потом увидим этот RoleBinding
  namespace: dev
subjects:
- kind: ServiceAccount  # Group, ServiceAccount
  name: jane             # имя чувствительно к регистру
roleRef:
  kind: Role     # явно указываем Role или ClusterRole
  name: admin           # а тут имя той Role или ClusterRole к которой мы биндимся
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-ken           # под этим именем мы потом увидим этот RoleBinding
  namespace: dev
subjects:
  - kind: ServiceAccount  # Group, ServiceAccount
    name: ken             # имя чувствительно к регистру
roleRef:
  kind: Role     # явно указываем Role или ClusterRole
  name: view           # а тут имя той Role или ClusterRole к которой мы биндимся
  apiGroup: rbac.authorization.k8s.io