#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-staging
#  namespace: cert-manager
#spec:
#  acme:
#    email: olga.kolpakova@gmail.com
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    privateKeySecretRef:
#      name: letsencrypt-staging
#    solvers:
#      - http01:
#          ingress:
#            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    email: olga.kolpakova@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: le-crt
#spec:
#  secretName: tls-secret
#  issuerRef:
#    kind: ClusterIssuer
#    name: letsencrypt-production
#  commonName: kuber.kochego.online
#  dnsNames:
#    - kuber.kochego.online